run: open() returned 134525586 instead of -1: FAILED
